/*USUARIOS*/

/* contraseña: 1234*/
INSERT INTO usuario (descripcion,email, pass, nombre, pais, foto, mediaGlobal, rol)
 VALUES
  ('Soy una persona muy aventurera, me gusta viajer por el Europa sobre todo. Me encantan los viajes culturales.', 'jorge_lacasta@hotmail.com', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Jorge', 'España', 'kurt-cobain.jpg',3, 'ADMIN'),
  ('Me gusta ir de viaje con mis amigos, los viajes que más me gustan son ir a la playa.', 'joan@joan.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Joan', 'España', 'messi.jpg',5, 'ADMIN'),
  ('Los viajes que suele hacer son viajes dentro de España. Me gusta ir de viaje con mis amigos y buscar mucha fiesta.', 'adriansanzperez.94@gmail.com', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Adrian', 'España', 'brad.jpg',4, 'ADMIN'),
  ('Me gusta mucho los viajes románticos y de relax. Dentro de poco me gustaría ir a decubrir américa latina.', 'maria@maria.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Donna', 'Italia', 'maria.jpg', 2, 'USER'),
  ('Llevo viajando por todo el mundo desde los 10 años. Me encantan los viajes gastronómicos y vivir aventuras.', 'sonia@sonia.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Amelie', 'Francia', 'sonia.jpg', 4.2, 'USER'),
  ('Me gustan los viajes tranquilos, de relax. Suelo buscar playas tranquilas o montaña. No me gustan las grandes ciudades', 'pepe@gmail.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Pepe', 'España', 'pepe.jpg', 3.2, 'USER'),
  ('Prefiero los viajes con amigos. Me gusta mucho la comida de otros paises y probar cosas nuevas', 'michael@gmail.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Michael', 'EEUU', 'michael.jpg', 4.8, 'USER'),
  ('Me gustan los viajes románticos con mi novio. Solemos hacer unos 2 o 3 viajes al año.', 'tania@gmail.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Tania', 'Rusia', 'tania.jpg', 2.7, 'USER'),
  ('Prefiero el turismo por mi país, recorrer primero todos los rincones de mi país natal.', 'angela@gmail.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'Angela', 'Alemania', 'angela.jpg', 1.8, 'USER'),
  ('Me encanta viajar por todo Europa y conocer gente nueva. Suele alojarme en los mejores hoteles de cada ciudad.', 'joao@gmail.es', '$2y$10$MohhVfbQPLo78ahT2topReJJCrD52w3JbkuWW6WP.2EZLVpgdjih6', 'João', 'Portugal', 'joao.jpg', 3.4, 'USER')
;

/*VIAJE*/
INSERT INTO viaje (pais_origen, ciudad_origen, pais_destino, ciudad_destino, foto, precio, transporte, descripcion, etiquetas, id_user)
 VALUES
  ('España', 'Madrid', 'España', 'Barcelona', 'barcelona1.jpg',200, 'Avion', 'Viaje express a Barcelona', 'Gastronómico/Con amig@s',1),
  ('España', 'Madrid', 'España', 'Santander, Bilbao, Burgos', 'santander.jpg',120, 'Coche', 'Viaje turistico por el Norte de España: Santander, Bilbao y Burgos', 'Aventuras/Con amig@s', 2),
  ('España', 'Valencia', 'España', 'Sevilla', 'sevilla.jpg', 180, 'Ave', 'Viaje a Sevilla', 'Cultural/Religioso', 3),
  ('España', 'Madrid', 'España', 'Segovia', 'segovia.jpg', 50, 'Coche', 'Viaje express a Segovia', 'Gastronómico/LowCost',4),
  ('España', 'Madrid', 'Italia', 'Roma', 'roma.jpg',300, 'Avion', 'Viaje a Roma, museos y cultura', 'Cultural/Romántico', 1),
  ('España', 'Madrid', 'España', 'Toledo', 'toledo.jpg',35, 'Coche', 'Viaje a Toledo', 'LowCost',2),
  ('España', 'Madrid', 'España', 'Barcelona', 'barcelona2.jpg',150, 'Autobus', '2 dias en Barcelona', 'Fiesta/Con amig@s',3),
  ('España', 'Salamanca', 'Portugal', 'Lisboa', 'lisboa.jpg',225, 'Coche', '3 dias en Lisboa', 'Romántico/Relax',4),
  ('España', 'Madrid', 'España', 'Granada', 'granada.jpg',140, 'Autobus', 'Viaje turistico a Granada', 'LowCost/Romántico/Religioso', 1),
  ('España', 'Madrid', 'Francia', 'Paris', 'paris.jpg',340, 'Avion', 'Viaje romantico a Paris', 'Romántico', 2),
  ('España', 'Madrid', 'Argentina', 'Buenos Aires, Iguazú y Ushuaia', 'argentina.jpg', 1460, 'Avion', 'Viaje de aventura por Argentina', 'Aventuras/Con amig@s/Cultural', 5),
  ('España', 'Madrid', 'Japón', 'Tokio, Osaka y Kioto', 'japon.jpg', 1735, 'Avion', 'Viaje de aventura por Japon', 'Aventuras/Gastronómico/Con amig@s', 5),
  ('Portugal', 'Oporto', 'España', 'Madrid', 'madrid.jpg', 210, 'Coche', 'Viaje gastronómico por Madrid', 'Gastronómico/Cultural', 10),
  ('España', 'Cadíz', 'España', 'Valencia', 'valencia.jpg', 175, 'Coche', 'Viaje de fiesta por Valencia', 'Fiesta/Con amig@s', 6),
  ('España', 'Barcelona', 'EEUU', 'New York', 'newyork.jpg', 1750, 'Avión', 'Descubriendo Nueva York', 'Cultural/Romántico', 7),
  ('España', 'Madrid', 'Rusia', 'San Petersburgo', 'SanPetersburgo.jpg', 1750, 'Avión', 'Descubriendo San Petersburgo', 'Religioso/Cultural', 8),
  ('España', 'Madrid', 'Alemania', 'Berlín', 'berlin.jpg', 450, 'Avión', 'Descubriendo Berlín', 'Gastronómico/LowCost', 9),
  ('España', 'Madrid', 'Portugal', 'Oporto', 'oporto.jpg', 216, 'Tren', 'Descubriendo Oporto', 'Aventura/LowCost', 10),
  ('Francia', 'Paris', 'Turquía', 'Estambul', 'estambul.jpg', 389, 'Avión', 'Descubriendo Estambul', 'Aventura/Cultural', 5),
  ('España', 'Barcelona', 'Italia', 'Milán, Florencia y Venecia', 'florencia.jpg', 645, 'Avión', 'Norte de Italia', 'Cultural', 6),
  ('España', 'Madrid', 'Egipto', 'El Cairo', 'egipto.jpg', 845, 'Avión', 'Descubriendo Egipto', 'Cultural/Aventuras', 8),
  ('España', 'Córdoba', 'España', 'Madrid', 'madrid.jpg', 102, 'Coche', 'Viaje cultural por Madrid', 'Cultural', 4),
  ('España', 'Madrid', 'Holanda', 'Ámsterdam', 'Amsterdam.jpg', 342, 'Avión', 'Viaje de aventuras por Ámsterdam', 'LowCost/Con amig@s', 7),
  ('España', 'Madrid', 'Inglaterra', 'Londres', 'londres.jpg', 392, 'Avión', 'Viaje de aventuras por Londres', 'LowCost', 9),
  ('España', 'Madrid', 'España', 'Córdoba', 'cordoba.jpg', 55, 'Coche', 'Viaje expres a Córdoba', 'Aventuras/Gastronómico/Con amig@s', 10),
  ('España', 'Valencia', 'Austria', 'Viena', 'viena.jpg', 715, 'Avión', 'Descubriendo Viena', 'Gastronómico/Con amig@s', 4),
  ('Italia', 'Roma', 'República Checa', 'Praga', 'praga.jpg', 328, 'Avión', 'Descubriendo Praga', 'Romántico', 8)
;

/*ITINERARIO*/
INSERT INTO itinerario (localizacion,alojamiento, manana, tarde, noche, id_viaje)
 VALUES
 ('Barcelona','hotel', 'aterrizaje en el aeropuerto y viaje al hotel', 'visita a la sagrada familia', 'paseo por las ramblas', 1),
 ('Barcelona','hotel', 'visita al parque Güell', 'paseo por la playa', 'vuelta al aeropuerto', 1),
 ('Santander', 'hotel', 'Viaje en coche a Santander', 'visita por Santander', 'vuelta al hotel', 2),
 ('Bilbao','hotel', 'Viaje en coche a Bilbao', 'visita por Bilbao', 'cena por Bilbao y vuelta al hotel', 2),
 ('Burgos','hotel', 'Viaje en coche a Burgos', 'visita por Burgos', 'vuelta a casa en coche', 2),
 ('Sevilla','hotel', 'Viaje en Ave a Sevilla', 'Paseo por el rio', 'cena de tapas', 3),
 ('Sevilla','hotel', 'Visita al barrio de Triana', 'Visita a la Plaza de España', 'Vuelta en Ave', 3),
 ('Segovia', 'hotel', 'Viaje en coche a Segovia', 'Paseo por la ciudad y comida en un bar tipico', 'Vuelta en coche a casa', 4),
 ('Roma','hotel', 'Viaje en Roma en avion', 'Visita al Coliseo', 'Cena en una pizzeria tipica', 5),
 ('Roma','hotel', 'Visita al Vaticano', 'Paseo por la ciudad, visita a la Piazza de Spagna', 'Cena el restaurante Di carli', 5),
 ('Roma','hotel', 'Visita al Panteon', 'Visita a la Fontana di Trevi', 'Vuelta a casa en avión', 5),
 ('Toledo', 'hotel', 'Viaje en coche a Toledo', 'Paseo por la ciudad y visita a la catedral', 'Cena en un restaurante típico y vueltaa casa en coche', 6),
 ('Barcelona','hotel', 'Viaje en autobus a Barcelona', 'Paseo por la ciudad, paseo por las ramblas', 'Cena en un TGB', 7),
 ('Barcelona','hotel', 'Visita al paque Güell', 'Visita a la casa Batlló', 'Vuelta a casa en autobus', 7),
 ('Lisboa','hotel', 'Viaje en coche a Portugal', 'Paseo por la ciudad', 'Cena en el restaurante Obrigrado, donde se puede ver toda la ciudad desde un mirador', 8),
 ('Sintra','hotel', 'Viaje en tren a Sintra', 'Visita a los palacios de Sintra', 'Vuelta a Lisboa', 8),
 ('Lisboa','hotel', 'Visita a Belen, donde estan los famosos pasteles de Belen', 'paseo por la playa y el puente', 'Vuelta a casa', 8),
 ('Granada','hotel', 'Viaje en autobus a Granada', 'visita al barrio del Albaicín', 'Cena de tapas en el bar los Manueles', 9),
 ('Granada','hotel', 'Visita a la Alhambra', 'Paseo por la ciudad', 'Vuelta a casa en autobus', 9),
 ('Paris','hotel', 'Viaje en avion a Paris', 'Paseo por la ciudad, comida en el restaurante Ratatouille', 'Visita a la Torre Eiffel', 10),
 ('Paris','hotel', 'Visita al museo Louvre', 'Visita al arco de triunfo', 'Paseo romantico por el Sena', 10),
 ('Paris','hotel', 'Visita al barrio de Montmartre', 'Visita a Notre Dame', 'Vuelta a casa en avión', 10),
 ('Buenos Aires','hotel', 'Viaje en avión', 'Viaje en avión', 'Llegada al aeropuerto', 11),
 ('Buenos Aires','hotel', 'Visita al barrio antiguo', 'Comida de la famosa carne argentina', 'Baile de un tango', 11),
 ('Iguazú','hotel', 'Viaje en avión a Iguazú', 'Llegada al aeropuerto', 'Cena en el restaurante Carne y Leña', 11),
 ('Iguazú','hotel', 'Visita a las cataratas de Iguazú', 'Visita a las cataratas de Iguazú', 'Vuelta al hotel', 11),
 ('Ushuaia','hotel', 'Viaje en avión a Ushuaia', 'Viaje en avión a Ushuaia', 'Llegada al aeropuerto', 11),
 ('Ushuaia','hotel', 'Visita el glaciar del Perito Moreno', 'Excursión para ver a los pingüinos', 'Cena romántica', 11),
 ('Ushuaia','hotel', 'Llegada al aeropuerto', 'Viaje en avión a casa', 'Viaje en avión a casa', 11),
 ('Tokio','hotel', 'Viaje en avión', 'Viaje en avión', 'Llegada al aeropuerto de Tokio', 12),
 ('Tokio','hotel', 'Visita el centro de Tokio', 'Visita el museo de Edo-Tokyo', 'Cena en el barrio de Matsuya el ramen típico', 12),
 ('Tokio','hotel', 'Viaje en bus al monte Fuji', 'Visita al monte Fuji', 'Cena de sushi en el restaurante Shinagawa', 12),
 ('Osaka','hotel', 'Viaje en tren a Osaka', 'Visita el centro de Osaka', 'Paseo nocturno por la ciudad', 12),
 ('Kioto','hotel', 'Viaje en tren a Kioto', 'Visita el Santuario Heian', 'Cena frente al Santuario', 12),
 ('Kioto','hotel', 'Llegada al aeropuerto', 'Vuelta a casa en avión', 'Vuelta a casa en avión', 12),
 ('Madrid','hotel', 'Llegada en coche al hotel', 'Comida de un bocata de calamares en Atocha', 'Paseo por la Gran Vía', 13),
 ('Madrid','hotel', 'Visita al museo Reina Sofía', 'Comida de un cocido madrileño en la Plaza Mayor', 'Tarde de cañas por la Latina', 13),
 ('Valencia','Camping', 'Viaje en coche a Valencia', 'Tarde en la playa', 'Fiesta en la discoteca Coco Loco', 14),
 ('Valencia','Camping', 'Comida de una paella', 'Tarde en la playa', 'Vuelta en coche a casa', 14),
 ('New York','Hotel', 'Llegada en avión al aeropuerto', 'Paseo por Central Park', 'Cena romántica en un restaurante italiano', 15),
 ('New York','Hotel', 'Visita a la estatua de la libertad', 'Paseo por Manhatan', 'Cena romántica en un restaurante frances', 15),
 ('New York','Hotel', 'Paseo por Times Square', 'Paseo por el Bronx', 'Vuelta a casa en avión', 15),
 ('San Petersburgo','Hotel', 'Llegada al aeropuerto', 'Paseo por la avenida Nevsky Prospect', 'Visita a la iglesia del salvador sobre la sangre derramada', 16),
 ('San Petersburgo','Hotel', 'Visita a la catedral de San Isaac', 'Visita al museo Hermitage', 'Cena en una pizzería', 16),
 ('San Petersburgo','Hotel', 'Visita a la plaza del palacio', 'Visita a la catedral Smolny', 'Vuelta al aeropuerto para coger el avión a casa', 16),
 ('Berlín','Hotel', 'Viaje en coche', 'Visita a la puerta de Brandenburgo', 'Paseo por el barrio antiguo', 17),
 ('Berlín','Hotel', 'Visita al Monumento a los judíos de Europa asesinados', 'Visita al muro de Berlín', 'Visita a East Side Gallery', 17),
 ('Berlín','Hotel', 'Visita Isla de los Museos', 'Visita a Alexanderplatz', 'Cena de las típicas salchichas alemanas con cerveza', 17),
 ('Berlín','Hotel', 'Visita a la Catedral', 'Visita al Fernsehturm de Berlín', 'Vuelta en avión a casa', 17),
 ('Oporto','Hotel', 'Llegada a la ciudad en tren', 'Visita al puente Don Luis I', 'Visita a la Catedral de Oporto', 18),
 ('Oporto','Hotel', 'Visita al palacio de la bolsa', 'Paseo por el barrio antiguo', 'Vuelta a la estación para coger el tren de vuelta a casa', 18),
 ('Estambul','Hotel', 'Llegada al aeropuerto', 'Compras en el gran bazar', 'Cena en un kebab', 19),
 ('Estambul','Hotel', 'Visita a Santa Sofía', 'Comida de falafel en el restaurante el Kahuj', 'Paseo por el río', 19),
 ('Estambul','Hotel', 'Visita a la plaza Taksim', 'Visita al palacion de Dolmabahçe', 'Vuelta al aeropuerto para coger el avión de regreso a casa', 19),
 ('Milán','Hotel', 'Llegada al aeropuerto de Milán', 'Visita al Duomo', 'Cena en una típica pizzería', 20),
 ('Florencia','Hotel', 'Llegada a la estación de tren de Florencia', 'Visita a Santa María de las Flores', 'Cena en el restaurante il bambino', 20),
 ('Venecia','Hotel', 'Llegada a la estación de tren de Venecia', 'Visita a la plaza de San Marcos', 'Vuelta al aeropuerto para coger el avión de regreso a casa', 20),
 ('El Cairo','Hotel', 'Llegada al aeropuerto de El Cairo', 'Visita al bazar Jan el-Jalili', 'Paseo por el barrio antiguo', 21),
 ('El Cairo','Hotel', 'Visita a las pirámides de Guiza', 'Comida en el restaurante Ramses', 'Cena romántica', 21),
 ('El Cairo','Hotel', 'Paseo en camello', 'Visita al museo egipcio de El Cairo', 'Vuelta al aeropuerto para coger el avión de regreso a casa', 21),
 ('Madrid','Apartamento', 'LLegada en coche a Madrid', 'Visita al Museo del Prado', 'Cena en el barrio de malasaña', 22),
 ('Madrid','Apartamento', 'Paseo por la Castellana', 'Visita al Museo de Reina Sofía', 'Vuelta a casa en coche', 22),
 ('Ámsterdam','Hotel', 'Llegada al aeropuerto de Ámsterdam', 'Visita al Museo van Gogh', 'Cena en una pizzería', 23),
 ('Ámsterdam','Hotel', 'Llegada al aeropuerto de Ámsterdam', 'Visita al Museo Casa de Rembrandt', 'Paseo por el río', 23),
 ('Ámsterdam','Hotel', 'Visita al parque Vondelpark', 'Visita al barrio rojo', 'Vuelta al aeropuerto a coger el avión de regreso', 23),
 ('Londres','Hotel', 'Llegada al aeropuerto de Londres', 'Visita al Big Ben', 'Cena de fish and chips', 24),
 ('Londres','Hotel', 'Visita al museo National Gallery', 'Paseo por el río', 'Cena en la hamburguesería The Queen', 24),
 ('Londres','Hotel', 'Visita al museo británico de historia', 'Visita a la Catedral', 'Vuelta al aeropuerto para coger el avión', 24),
 ('Córdoba','Hotel', 'Llegada en coche y visita a la Mezquita', 'Paseo por el barrio antiguo', 'Cena en el restaurante la alegría, y vuelta a casa en coche', 25),
 ('Viena','Hotel', 'Llegada al aeropuerto de Viena', 'Visita al palacio de Hofburg', 'Cena romántica', 26),
 ('Viena','Hotel', 'Compras por el mercado', 'Visita a la Catedral de San Estebán', 'Paseo por el río', 26),
 ('Viena','Hotel', 'Visita al ayuntamiento de Viena', 'Visita al palacio de Schönbrunn', 'Vuelta al aeropuerto para coger el avión', 26),
 ('Praga','Hotel', 'Llegada al aeropuerto de Praga', 'Visita al Castillo de Praga', 'Cena romántica', 27),
 ('Praga','Hotel', 'Visita al reloj astronómico de Praga', 'Visita a la plaza de la ciudad vieja', 'Paseo por el río', 27),
 ('Praga','Hotel', 'Visita al puente Carlos', 'Comida en el restaurante Moldava', 'Vuelta al aeropuero a coger el avión de regreso a casa', 27)
;

/*PUNTO DE RUTA*/
INSERT INTO fotosIT (ruta, id_itinerario)
 VALUES
 ( 'barcelona3.jpg', 1),
 ('barcelona2.jpg' , 2),
 ( 'santander2.jpg', 3),
 ( 'bilbao.jpg', 4),
 ( 'burgos.jpg', 5),
 ( 'sevilla2.jpg', 6),
 ( 'triana.jpg', 7),
 ('segovia2.jpg', 8),
 ( 'vaticano.jpg', 9),
 ('Fontana_di_Trevi.jpg', 10),
 ( 'panteon.jpg', 11),
 ('toledo2.jpg', 12),
 ( 'barcelona3.jpg',13),
 ( 'sagradafamilia.jpg', 14),
 ( 'lisboa2.jpg', 15),
 ('sintra.jpg', 16),
 ('belem.jpg', 17),
 ('cathedral_granada.jpg', 18),
 ('alhambra.jpg', 19),
 ( 'paris4.jpg', 20),
 ( 'paris2.jpg', 21),
 ('louvre.jpg', 22),
 ('avion.jpg', 23),
 ('buenos_aires.jpg', 24),
 ('154252_iguaz_790856.jpg', 25),
 ('Iguazu-Falls.jpg', 26),
 ('ushuaia.jpg', 27),
 ('Glaciar-Perito-Moreno-cómo-llegar-1.jpg', 28),
 ('avion2.jpg', 29),
 ('tokyo_aerport.jpg', 30),
 ('tokio.jpg', 31),
 ('Monte-Fuji.jpg', 32),
 ('osaka.jpg', 33),
 ('kioto.jpg', 34),
 ('avion3.jpg', 35),
 ('calamares.jpg', 36),
 ('reina sofia.jpg', 37),
 ('playa.jpg', 38),
 ('paella.jpg', 39),
 ('centralpark.jpg', 40),
 ('estatua.jpg', 41),
 ('timessquare.jpg', 42),
 ('iglesia.jpg', 43),
 ('isaac.jpg', 44),
 ('plaza.jpg', 45),
 ('puerta.jpg', 46),
 ('muro.jpg', 47),
 ('salchicha.jpg', 48),
 ('catedral.jpg', 49),
 ('catedral-oporto.jpg', 50),
 ('palacio.jpg', 51),
 ('bazar.jpg', 52),
 ('sofia.jpg', 53),
 ('plaza-taksim.jpg', 54),
 ('milan.jpg', 55),
 ('santamaria.jpg', 56),
 ('marcos.jpg', 57),
 ('bazar.jpg', 58),
 ('piramides.jpg', 59),
 ('camello.jpg', 60),
 ('maseodelprado.jpg', 61),
 ('guernica.jpg', 62),
 ('museovangogh.jpg', 63),
 ('plazadam.jpg', 64),
 ('barriorojo.jpg', 65),
 ('bigben.jpg', 66),
 ('national.jpg', 67),
 ('museobritanico.jpg', 68),
 ('mezquita.jpg', 69),
 ('palacio-hofburg.jpg', 70),
 ('san-esteban.jpg', 71),
 ('Schönbrunn.jpg', 72),
 ('castillo.jpg', 73),
 ('plaza-praga.jpg', 74),
 ('puente-carlos.jpg', 75)
;

/*COMENTARIO*/
INSERT INTO comentario (texto, fecha, id_user, id_viaje)
 VALUES
 ('Que guapo el viaje', '2020-01-01', 2, 1),
 ('Me gusta mucho Barcelona', '2020-02-04', 4, 1),
 ('Muy barato !', '2020-12-13', 3, 2),
 ('¿Me recomiendas ir en verano?', '2020-10-05', 4, 2),
 ('¿Que sitio recomiendas para comer?', '2020-11-02', 4, 3),
 ('Como mola', '2020-11-22', 1, 4),
 ('oleeeeee', '2020-12-26', 2, 4),
 ('Chulisimo el viaje', '2020-11-06', 1, 5),
 ('¿Recomendarias algo más para visitar?', '2020-11-06', 4, 6),
 ('oleeeee', '2020-12-13', 4, 7),
 ('Maquinaaaa', '2020-12-13', 1, 8),
 ('Ole tu', '2020-06-21', 4, 8),
 ('¿recomiendas algun sitio para comer?', '2020-12-13', 3, 8),
 ('Como mola se merece una ola', '2020-11-16', 2, 9),
 ('Me encanta este viaje', '2020-10-05', 3, 9),
 ('Me gusta mucho este viaje, seguramente lo haga pronto', '2020-09-05', 3, 10),
 ('¿Recomiendas ur más días?', '2020-010-05', 2, 11),
 ('I love it', '2020-010-05', 1, 12),
 ('I love it', '2020-010-05', 4, 13),
 ('Como mola el viaje', '2020-010-05', 5, 13),
 ('Me encanta', '2020-010-05', 6, 14),
 ('Chulisimo', '2020-010-05', 7, 14),
 ('Increible viaje', '2020-010-05', 8, 15),
 ('Guapisimo el viaje', '2020-010-05', 10, 15),
 ('A mi este viaje no me gusto nada', '2020-010-05', 2, 15),
 ('Buenisimo', '2020-010-05', 7, 16),
 ('¿Sabes algún sitio para cenar?', '2020-010-05', 5, 16),
 ('Oleee', '2020-010-05', 2, 16),
 ('A mi no me gusta este viaje, es muy caro', '2020-010-05', 8, 16),
 ('Muy barato', '2020-010-05', 9, 17),
 ('Muy caro', '2020-010-05', 6, 17),
 ('Me gusta mucho', '2020-010-05', 5, 17),
 ('Muy barato !', '2020-12-13', 3, 18),
 ('¿Me recomiendas ir en verano?', '2020-10-05', 4, 18),
 ('¿Que sitio recomiendas para comer?', '2020-11-02', 4, 19),
 ('Como mola', '2020-11-22', 1, 19),
 ('oleeeeee', '2020-12-26', 2, 19),
 ('Chulisimo el viaje', '2020-11-06', 1, 20),
 ('¿Recomendarias algo más para visitar?', '2020-11-06', 4, 21),
 ('oleeeee', '2020-12-13', 4, 22),
 ('Maquinaaaa', '2020-12-13', 1, 22),
 ('Ole tu', '2020-06-21', 4, 22),
 ('¿recomiendas algun sitio para comer?', '2020-12-13', 3, 23),
 ('Como mola se merece una ola', '2020-11-16', 2, 23),
 ('Me encanta este viaje', '2020-10-05', 3, 23),
 ('Me gusta mucho este viaje, seguramente lo haga pronto', '2020-09-05', 3, 24),
 ('¿Recomiendas ur más días?', '2020-010-05', 2, 25),
 ('I love it', '2020-010-05', 1, 25)
;

/*VALORACION*/
INSERT INTO valoracion (puntuacion, id_user, id_viaje)
 VALUES
  (5, 3, 1),
  (4, 2, 2),
  (4, 4, 2),
  (2, 1, 3),
  (4, 2, 3),
  (5, 3, 4),
  (4, 4, 4),
  (1, 1, 5),
  (2, 1, 6),
  (5, 3, 6),
  (3, 3, 6),
  (5, 1, 6),
  (4, 4, 7),
  (3, 1, 8),
  (4, 2, 8),
  (4, 3, 9),
  (5, 1, 9),
  (5, 1, 9),
  (2, 2, 10),
  (4, 3, 10),
  (4, 3, 11),
  (5, 2, 11),
  (5, 1, 12),
  (4, 2, 12),
  (5, 4, 12),
  (2, 6, 13),
  (4, 5, 13),
  (1, 1, 14),
  (4, 2, 14),
  (4, 6, 15),
  (3, 7, 15),
  (5, 8, 15),
  (4, 2, 16),
  (2, 3, 16),
  (3, 4, 16),
  (3, 5, 17),
  (4, 4, 17),
  (4, 6, 17),
  (3, 1, 17),
  (2, 1, 18),
  (4, 2, 18),
  (5, 3, 19),
  (4, 4, 19),
  (1, 1, 20),
  (2, 1, 20),
  (5, 3, 20),
  (3, 3, 20),
  (5, 1, 20),
  (4, 4, 21),
  (3, 1, 22),
  (4, 2, 22),
  (4, 3, 22),
  (5, 1, 22),
  (5, 1, 23),
  (2, 2, 23),
  (4, 3, 24),
  (4, 3, 24),
  (5, 2, 24),
  (5, 1, 24),
  (4, 2, 24),
  (5, 4, 25),
  (2, 6, 25),
  (4, 5, 25),
  (1, 1, 25)
;

/*FAVORITOS*/
INSERT INTO favoritos (id_user, id_viaje)
 VALUES
 (1, 1),
 (2, 4),
 (3, 1),
 (4, 7),
 (3, 8),
 (5, 2),
 (2, 12)
;
